version: 1.1.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
test:
  assemblies:
    only:
    - '**\bin\release\Xunit.Repeat.Tests.dll'
artifacts:
- path: '**\*.nupkg'
  name: NuGet package
deploy:
- provider: NuGet
  api_key:
    secure: CHBZqd5tvF40eTOeX4S85Xb4U7FoaZMMxD65HjHhPgQlzLVXoYnEmmdReehmivdI
  skip_symbols: true
  artifact: $(temp_path)\*.nupkg